# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LEOCHARRE-Dev
version:      1.04
version_from: lib/LEOCHARRE/Dev.pm
installdirs:  site
requires:
    Cwd:                           3.01
    Data::Dumper:                  2.121
    Devel::Symdump:                2.06
    Exporter:                      5.58
    File::Find::Rule:              0.30
    LEOCHARRE::Class::Accessors:   0
    Module::Info:                  0
    Smart::Comments:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
