# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LEOCHARRE-Dev
version:      1.03
version_from: lib/LEOCHARRE/Dev.pm
installdirs:  site
requires:
    File::Find::Rule:              0
    LEOCHARRE::CLI:                0
    LEOCHARRE::DEBUG:              1.02
    Module::Info:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
