--- #YAML:1.0
name:               LEOCHARRE-Dev
version:            1.13
abstract:           tools to help manage distro development and maintenance
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AppConfig::Std:       1.07
    Carp:                 1
    Class::Inspector:     1.23
    Cwd:                  3
    Data::Dumper:         2.121_02
    Devel::ModInfo:       0
    Devel::Symdump:       2.07
    DMS:                  1.56
    Exporter:             5
    ExtUtils::MakeMaker:  6
    File::Basename:       2.73
    File::Find:           1.07
    File::Find::Rule:     0.30
    File::Path:           2.07
    File::Trash:          1.06
    Getopt::Std::Strict:  1.01
    HTTP::Request::Common:  1.28
    HTTP::Status:         1.28
    LEOCHARRE::Class2:    1.19
    LEOCHARRE::CLI:       1.19
    LEOCHARRE::CLI2:      1.07
    LEOCHARRE::DEBUG:     1.12
    LEOCHARRE::Dir:       1.07
    LEOCHARRE::Test:      1.10
    LWP::UserAgent:       2.036
    Module::Info:         0.31
    Net::FTP:             2.75
    Smart::Comments:      1
    Term::ReadKey:        2.30
    Test::Simple:         0
    Time::Format:         1.09
    WWW::CPAN:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
