# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LEOCHARRE-Dev
version:      1.07
version_from: lib/LEOCHARRE/Dev.pm
installdirs:  site
requires:
    AppConfig::Std:                1.07
    Bogus:                         0
    Carp:                          1.04
    Cwd:                           3.12
    Data::Dumper:                  2.121_08
    Devel::AssertEXE:              0
    Devel::ModInfo:                0
    Devel::Symdump:                2.07
    Exporter:                      5.58
    ExtUtils::MakeMaker:           6.30
    File::Basename:                2.74
    File::Find:                    1.10
    File::Find::Rule:              0.30
    File::Path:                    1.08
    HTTP::Request::Common:         1.26
    HTTP::Status:                  1.28
    LEOCHARRE::CLI:                1.18
    LEOCHARRE::DEBUG:              1.11
    LWP::UserAgent:                2.033
    Module::Info:                  0.3
    Net::FTP:                      2.75
    Smart::Comments:               v1.0.2
    Term::ReadKey:                 2.30
    Test2:                         0
    Test::Simple:                  0.7

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
